[package]
name = "verilator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.73"

[build-dependencies]
cc = "1.0.73"
